GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/15

###

POST  http://localhost:3000/subscribers
Content-Type: application/json

{
    "name" : "raad",
    "subscribedToChannel" : "Not Web Dev"
}
###

POST  http://localhost:3000/subscribers
Content-Type: application/json

{
    "name" : "walid",
    "subscribedToChannel" : "Web Dev"
}

